spring:
  datasource:
    driver-class-name: org.h2.Driver # H2 데이터베이스 드라이버 사용
    # [mem:baton] 메모리 DB 사용 및 이름 지정
    # [MODE=MySQL] MySQL 쿼리 문법 호환성 제공
    # [DB_CLOSE_DELAY=-1] 애플리케이션이 실행 중인 동안 DB 데이터 유지
    # [DATABASE_TO_UPPER=FALSE] H2가 테이블/컬럼명을 강제로 대문자로 바꾸는 것을 방지 (MySQL 환경 비대칭 해결)
    url: jdbc:h2:mem:baton;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE
    username: sa # H2 기본 접속 계정
    password:
  h2:
    console:
      enabled: true # 브라우저를 통한 H2 관리자 콘솔 접속 활성화
      path: /h2-console # 콘솔 접속 엔드포인트 (http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: create-drop # 실행 시 엔티티를 바탕으로 테이블 생성, 종료 시 테이블 Drop (로컬 테스트용)
    properties:
      hibernate:
        format_sql: true # 출력되는 쿼리를 읽기 편하게 줄바꿈하여 정렬
        use_sql_comments: true # 쿼리가 실행된 이유(어떤 동작인지)를 주석으로 함께 출력
        highlight_sql: true # 콘솔에 찍히는 쿼리문에 색상을 입혀 가독성 향상

logging:
  level:
    # show-sql: true 대신 로깅 프레임워크를 사용하여 시간, 스레드 등의 정보와 함께 안전하게 쿼리 기록
    org.hibernate.SQL: debug
    # 쿼리의 '?' 자리에 들어가는 실제 파라미터 값(바인딩 파라미터)을 로그로 출력하여 디버깅 용이
    org.hibernate.orm.jdbc.bind: trace