spring:
  config:
    import: optional:classpath:application-secret.yaml
    # 🚀 운영 배포 환경을 위해 통로만 추가

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: info