spring:
  application:
    name: baton
  profiles:
    active: local
  config:
    import: optional:classpath:application-secret.yaml

credit:
  initial-amount: 10000 # 초기 크레딧 금액 설정

escrow:
  confirmation-expiry-days: 7 # 구매 확정 만료 일수

user:
  initial-trust-score: 50.00

s3:
  presigned-put-expiry-minutes: 5 # 클라이언트 S3 업로드 유효 시간 (분)
  presigned-get-expiry-hours: 3 # 조회 URL 유효 시간 (시간)
